### ISSUE TITLE
All the Simulation links are broken

### ISSUE THREAD

**Issue by madhavipuliraju** [openedx-vlead/open-edx-virtual-proteomics-lab-iitb#1]
All the Simulation Links are broken

**Comment by sanchita-dixit** [comment]
The simulation links broke because this lab was rehosted on AWS after it was initially hosted on the institute servers itself. But the new experiment URLs were not updated in the Edx platform. Even now the links of a particular experiment are same for every section e.g. introduction, theory, simulation, references etc. All the simulator sections are empty for this lab. I have updated new URLs for simulations, still they are referring to empty sections. This is the issue with the lab itself, which is out of our control.
